### ISSUE TITLE
Write xyz from gaussian coordinates bug with versions

### ISSUE THREAD

**Issue by CalCraven** [GOMC-WSU/MoSDeF-dihedral-fit#122]
Working with this function with @GuiLingfeng, there's some buggy behavior with parsing different gaussian files. The first thing is the title, which is grabbed from [this line in the file](https://github.com/GOMC-WSU/MoSDeF-dihedral-fit/blob/3efeca884a80d72180b8f622b43d80d47991b1e4/mosdef_dihedral_fit/utils/file_read_and_write.py#L866), and assumes the title "Dihedral Scan", whereas it can be set to anything. This will cause `dihedral_scan_line = m` to never be run, so later checks for dihedral_scan_line is None will be incorrect, such as [this line](https://github.com/GOMC-WSU/MoSDeF-dihedral-fit/blob/3efeca884a80d72180b8f622b43d80d47991b1e4/mosdef_dihedral_fit/utils/file_read_and_write.py#L948).

Also bumping into some issue where indenting [this statement](https://github.com/GOMC-WSU/MoSDeF-dihedral-fit/blob/3efeca884a80d72180b8f622b43d80d47991b1e4/mosdef_dihedral_fit/utils/file_read_and_write.py#L1035-L1040) one more outwards fixed the error
```
File "/Users/griffin/packages/MoSDeF-dihedral-fit/mosdef_dihedral_fit/utils/file_read_and_write.py", line 1039, in get_gaussian_log_file_data
    last_coordinates_ang_list
UnboundLocalError: cannot access local variable 'last_coordinates_ang_list' where it is not associated with a value
```

GuiLingfeng will post the file this was happening with below. But essentially, the if statement in 1035 has a chance to be called, when line 1016 has never passed yet, so the that last_coordinates_ang_list is never set. Not sure why it's being called early though, so would like some input if one more indent is a solution, or if leaving the line of code where it is important for some other functionality.

**Comment by GuiLingfeng** [comment]
Thanks @CalCraven for the issue description. I am posting my gaussian output file here for the developers to test. If I encounter any further issue, I will also post here. 
[scan_perfluorodimethylether.log](https://github.com/user-attachments/files/16817715/scan_perfluorodimethylether.log)

**Comment by bc118** [comment]
Are you running this to fit the dihedral with a mol2 file of just running "get_gaussian_log_file_data" function?

**Comment by GuiLingfeng** [comment]
> Are you running this to fit the dihedral with a mol2 file of just running "get_gaussian_log_file_data" function?

I'm fitting the dihedral with a mol2.

**Comment by bc118** [comment]
@CalCraven @GuiLingfeng Hello! Thanks for catching this.  I believe this PR ( https://github.com/GOMC-WSU/MoSDeF-dihedral-fit/pull/123) fixes the issue and makes it read correctly now.  

Pleas see the attached Excel file for the quick output analysis in the PR, and feel free to check it yourself also.  Can you please confirm that this now is outputting the data correctly ?

**Comment by GuiLingfeng** [comment]
> @CalCraven @GuiLingfeng Hello! Thanks for catching this. I believe this PR ( #123) fixes the issue and makes it read correctly now.
> 
> Pleas see the attached Excel file for the quick output analysis in the PR, and feel free to check it yourself also. Can you please confirm that this now is outputting the data correctly ?
> 
> [angle_vs_energy.zip](https://github.com/user-attachments/files/16824900/angle_vs_energy.zip)

I have tested the PR #123 myself and can confirm now it is reading my Gaussian log file correctly. And the plot @bc118 generated looks absolutely fine.
