### ISSUE TITLE
Auto-detection of required binaries

### ISSUE THREAD

**Issue by daico007** [GOMC-WSU/MoSDeF-dihedral-fit#26]
We can utilize `shutil.which()` to auto detect required binary to run certain module/function (currently we are using `os.path.isfile` and make it check for a provided path, and only for tests). The implementation could be something similar to https://github.com/MaginnGroup/mosdef_cassandra/blob/master/mosdef_cassandra/utils/detect.py.

**Comment by bc118** [comment]
This was done in the testing files
