### ISSUE TITLE
References to readthedocs in readme

### ISSUE THREAD

**Issue by CalCraven** [GOMC-WSU/MoSDeF-dihedral-fit#41]
As noted by @bc118, we'll have to add some additional links once the readthedocs are published. 
Example below brought up in regards to citations in #36.

> We should just add a link to the citations listed in the MoSDeF_dihedral_fit docs, which include all mosdef packages, and vmd.... We can add the docs link once they are published...
> 
> This is currently what the docs say (not to add here, just for reference):
> 
> ```
> * `MoSDeF-GOMC <https://github.com/GOMC-WSU/MoSDeF-GOMC>`_ -- Python software for the creation of scientific workflows for the Monte Carlo simulation engine GOMC
> 
> * `mBuild <https://mbuild.mosdef.org/en/stable/>`_ -- A hierarchical, component based molecule builder
> 
> * `foyer <https://foyer.mosdef.org/en/stable/>`_ -- A package for atom-typing as well as applying and disseminating forcefields
> 
> * `GMSO <https://gmso.mosdef.org/en/stable/>`_ -- Flexible storage of chemical topology for molecular simulation
> 
> * `forcefield-utilities <https://github.com/mosdef-hub/forcefield-utilities/>`_
> 
> * `Visual Molecular Dynamics (VMD) <https://www.ks.uiuc.edu/Research/vmd/>`_
> 
> * `vmd-python <https://github.com/Eigenstate/vmd-python>`_
> ```

**Comment by bc118** [comment]
@CalCraven Add what citations here, and I will add to the PR, then get them published for MOSDEF and I will get mosdef-gomc and VMD
