### ISSUE TITLE
Add pytest as a dependancy to the next release version 

### ISSUE THREAD

**Issue by bc118** [GOMC-WSU/MoSDeF-dihedral-fit#84]
Add pytest as a dependancy to the next release version

**Comment by bc118** [comment]
Add pytest to be built as a dependency in the next version.

**Comment by atomfold** [comment]
@bc118 notes: LAST CHANGE TO DO ON  CONDA-FORGE FEEDSOCK:  

This exists on the main 'environment.yml' and in the docs one 'docs/environment_docs.yml'.  It needs added to the conda-forge feedstock **_(add `pytest` and  `pytest-cov`)_** at the after all changes are done release script.

**Comment by bc118** [comment]
Completed with PR https://github.com/conda-forge/mosdef-dihedral-fit-feedstock/pull/1
