### ISSUE TITLE
Suggestion : Add coverage badge to readme

### ISSUE THREAD

**Issue by naik-aakash** [GOMC-WSU/MoSDeF-dihedral-fit#95]
## Part of JOSS review : https://github.com/openjournals/joss-reviews/issues/6970

Dear developers,

I was thinking, it would be great it coverage badge is added to the readme for a quick overview. Not required to be added, is just an suggestion from my end. 😄

**Comment by bc118** [comment]
We are trying to keep these consistent across the MoSDeF ecosystem (MoSDeF-dihedral-fit, MoSDeF-GOMC, GMSO, foyer, mbuild, etc.). Therefore, we will consider adding later when we revise all of them.
