### ISSUE TITLE
Suggestion : Tests 

### ISSUE THREAD

**Issue by naik-aakash** [GOMC-WSU/MoSDeF-dihedral-fit#98]
## Part of JOSS review : https://github.com/openjournals/joss-reviews/issues/6970

Dear developers,

I feel it would be great if tests are added to check for exceptions raised as well. From the current coverage report , I see most of the missing lines are from exceptions and would be better to have tests for these lines as well. 
 
![Screenshot 2024-07-19 200817](https://github.com/user-attachments/assets/b1809f4e-013a-4081-a0e1-504a27afae76)

**Comment by daico007** [comment]
Hi @naik-aakash, I have added more tests specifically on the exceptions raised in our main code in #106 and #120. Please let us know if you think if there's any area that we missed and needed more testing.

**Comment by bc118** [comment]
I will add that some of the missing coverage parts in code that I write come from “catch all” checks; in which case, I do not know how the code would end up in that error or warning.  However, if someone makes an error in the code, something that changes in in unexpected ways or allows the user to enter problematic options, it may catch some of these conditions.

**Comment by bc118** [comment]
Closing as reviewer provided thumbs up on the added tests and general  “catch all” checks that are hard to replicate. 

More notes on this and other Reviewer Requests (provided as Issues) are located here https://github.com/GOMC-WSU/MoSDeF-dihedral-fit/issues/101
