### ISSUE TITLE
Suggestions : Documentation and Tests

### ISSUE THREAD

**Issue by naik-aakash** [GOMC-WSU/MoSDeF-dihedral-fit#99]
## Part of JOSS review : https://github.com/openjournals/joss-reviews/issues/6970

Dear developers,

Do not know how much of additional work it can be. I was thinking would it be feasible to add some examples for dihedral fitting using other forcefields i.e.,  CHARMM, TraPPE, AMBER, Mie, and Exp6  to the documentation ? 

And also include some tests for these. I noticed MIE and OPLS are already included in tests, but could not find tests for other forcefields mentioned in the paper. (It is possible I could be missed the tests, kindly correct me if am mistaken on this.)

**Comment by bc118** [comment]
Hello!

Thank you for your review and comments!  We will complete all of these that are feasible to completed. We started a issue checklist with all the reviewer comments, so we can address them and write our teams notes here https://github.com/GOMC-WSU/MoSDeF-dihedral-fit/issues/101.

If we need any clarifications, we will kindly ask for them.  Thank you!

**Comment by daico007** [comment]
Addressed in #108
